### ISSUE TITLE
The loss function in the COCA/models/COCA/coca_trainer/trainer.py is not same as paper.

### ISSUE THREAD

**Issue by wiwi** [ruiking04/COCA#4]
Detailed at line 184 and 185 of models/COCA/coca_trainer/trainer.py, as following:
sigma_aug1 = torch.sqrt(feature1.var([0]) + 0.0001)
sigma_aug2 = torch.sqrt(distance_dec1.var([0]) + 0.0001)

Refer to the paper, it should be :
sigma_aug1 = torch.sqrt(distance1.var([0]) + 0.0001)
sigma_aug2 = torch.sqrt(distance_dec1.var([0]) + 0.0001)

Am I right?

**Comment by ruiking04** [comment]
Thanks for your interest in our work.
Sorry, the code here is indeed a bit wrong, but it should be as follows：
sigma_aug1 = torch.sqrt(feature1.var([0]) + 0.0001)
sigma_aug2 = torch.sqrt(feature_dec1.var([0]) + 0.0001)
Because we want to ensure that the variance of the projection vectors is greater than a threshold, rather than collapsing into a single point.
We have also made some changes to the paper and will update the latest version soon.

**Comment by wiwi** [comment]
Thank your response. Your revision is right, I made a mistake. Looking forward to your new version.
